x = str("Hello World")
y = int(11)
z = float(11.5)
a= complex(1j)
b= list(("apple", "banana", "cherry"))
c = (("apple", "banana", "cherry"), ("dog", "cat", "mouse"))

d = range(6)
e = dict(name="John", age=36)
f = set(("apple", "banana", "cherry"))
g = frozenset([("apple", "banana", "cherry"), ("dog", "cat", "mouse")])

h = bool(5)
i = bytes(5)
j = bytearray(5)    
k = memoryview(bytes(5))
print(type(x))
print(type(y))
print(type(z))
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))
print(type(j))
print(type(k))
