firstName  = input("Enter your first name: ")
lastName = input("Enter your last name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
print("\nProfile Summary:")
print(f"Name: {firstName} {lastName}")
print(f"Age: {age}")
print(f"City: {city}")
print("Profile generated successfully!")
